version: "3.3"

services:
  musicbotdiscordv3:
    image: musicbot
    container_name: musicbot
    build: .
    restart: unless-stopped
    env_file: .env
    labels:
      - traefik.enable=false
      - "com.centurylinklabs.watchtower.enable=false"
